server:
  port: ${PORT}
  servlet:
    context-path: '/'
  forward-headers-strategy: framework

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URI}
          predicates:
            - Path=/auth/**, /users/**
        - id: auth-service-swagger
          uri: ${AUTH_SERVICE_URI}
          predicates:
            - Path=/auth-service/v3/api-docs/**
          filters:
            - StripPrefix=1

        - id: products-service
          uri: ${PRODUCTS_SERVICE_URI}
          predicates:
            - Path=/products/**
        - id: products-service-swagger
          uri: ${PRODUCTS_SERVICE_URI}
          predicates:
            - Path=/products-service/v3/api-docs
          filters:
            - StripPrefix=1

        - id: carts-service
          uri: ${CARTS_SERVICE_URI}
          predicates:
            - Path=/carts/**
        - id: carts-service-swagger
          uri: ${CARTS_SERVICE_URI}
          predicates:
            - Path=/carts-service/v3/api-docs
          filters:
            - StripPrefix=1

        - id: notifications-service
          uri: ${NOTIFICATIONS_SERVICE_URI}
          predicates:
            - Path=/api/v1/notifications/**, /api/v1/emails/**
        - id: notifications-service-swagger
          uri: ${NOTIFICATIONS_SERVICE_URI}
          predicates:
            - Path=/notifications-service/swagger-json
          filters:
            - StripPrefix=1

        - id: discounts-service
          uri: ${DISCOUNTS_SERVICE_URI}
          predicates:
            - Path=/api/v1/discounts/**, /api/v1/offers/**
        - id: discounts-service-swagger
          uri: ${DISCOUNTS_SERVICE_URI}
          predicates:
            - Path=/discounts-service/swagger-json
          filters:
            - StripPrefix=1

        - id: orders-service
          uri: ${ORDERS_SERVICE_URI}
          predicates:
            - Path=/orders/**
        - id: orders-service-swagger
          uri: ${ORDERS_SERVICE_URI}
          predicates:
            - Path=/orders-service/swagger/doc.json
          filters:
            - StripPrefix=1

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /auth-service/v3/api-docs
        name: Auth Service
      - url: /products-service/v3/api-docs
        name: Products Service
      - url: /carts-service/v3/api-docs
        name: Carts Service
      - url: /notifications-service/swagger-json
        name: Notification Service
      - url: /discounts-service/swagger-json
        name: Discounts Service
      - url: /orders-service/swagger/doc.json
        name: Orders Service
